version: '3.8'

services:
  dev:
    build: .
    # image: lmwafer/orb-slam-3-ready:1.1-ubuntu18.04
    container_name: orb-slam-dev
    volumes:
      - .:/ORB_SLAM3
      - /mnt/wslg:/mnt/wslg
      - /tmp/.X11-unix:/tmp/.X11-unix
    environment:
      - DISPLAY=$DISPLAY
      - WAYLAND_DISPLAY=$WAYLAND_DISPLAY 
      - XDG_RUNTIME_DIR=$XDG_RUNTIME_DIR
      - PULSE_SERVER=$PULSE_SERVER
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
    command: /bin/sh -c "while sleep 1000; do :; done"