version: '3.7'

services:
  realsense-ready:
    container_name: realsense-container
    image: lmwafer/realsense-ready:2.0-ubuntu18.04
    restart: always
    privileged: true
    ports:
      - "8084:8084"
    environment:
      - DISPLAY=$DISPLAY                  # Give access to display
      - QT_X11_NO_MITSHM=1
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix     # Give access to X11
      - /dev:/dev:ro
    stdin_open: true                      # Equivalent to "docker run -i"
    tty: true                             # Equivalent to "docker run -t"

    deploy:                               # In response to libGL error: No matching fbConfigs or visuals found
      resources:                          #                libGL error: failed to load driver: swrast
        reservations:                     #                Could not open OpenGL window, please check your graphic drivers or use the textual SDK tools
          devices:
          - driver: nvidia
            device_ids: ['0']             # This ID may change on different machines : `lshw -c display` for more info
            capabilities: [gpu]